permalink: /:year/:month/:title
markdown: redcarpet
pygments: true
exclude: ['Rakefile', 'CNAME', 'README.md', 'LICENSE', 'config.rb', 'scss/']

url: http://aniketpant.com

name: "Aniket Pant"
description: "Notes and Essays by a developer"