permalink: /posts/:title
exclude: ["assets/styles/sass/", "config.rb", "CNAME"]
auto: true
markdown: kramdown

title: "Aniket Pant"
tagline: "Rawrrr"
author:
 name: "Aniket Pant"
 email: "me@aniketpant.com"
 github: "aniketpant"
 twitter: "aniket_pant"
 facebook: "aniket.pant"